In [20]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [36]:
import pandas as pd
iris = load_iris()
iris_data = iris.data # 데이터 
iris_label = iris.target # 정답 
#print(iris_data)
#print(iris_label)

In [22]:
# iris_data 행 / 열 , iris.feature_names는 열 이름 리스트 ['sepal length (cm)', 'sepal width (cm)',
iris_df = pd.DataFrame(data=iris_data , columns =iris.feature_names)
iris_df['label']=iris.target # 정답값 
iris_df.head(7)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
5                5.4               3.9                1.7               0.4   
6                4.6               3.4                1.4               0.3   

   label  
0      0  
1      0  
2      0  
3      0  
4      0  
5      0  
6      0

In [23]:
#1.데이터 분할 train_test_split() -> 학습데이터 , 테스트테이터 분할
from sklearn.model_selection import train_test_split
X_train , X_test ,y_train , y_test = train_test_split(iris_data,iris_label,test_size=0.2,random_state=11)

In [24]:
# 의사 결정 트리 클래스 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

In [25]:
#2.학습 수행 : 객체의 fit 함수
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

In [26]:
#3. 예측 수행 
pred = dt_clf.predict(X_test) # 모델이 예상한 정답지 - 예측한 클래스 번호 리스트 
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [27]:
# 4. 평가-정확도 측정 : accuracy_score() 
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, pred) # y_test : 실제 정답 / pred : 모델의 예측값 
print(f'예측 정확도: {accuracy:.4f}')

예측 정확도: 0.9333


In [28]:
from sklearn.datasets import load_iris
iris_data = load_iris()# 데이터 딕셔너리 형태
keys = iris_data.keys() # 서랍이름표 느낌 : 이 딕셔너리가 어떤 카테고리들로 이루어져 있는지 
print(keys)

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [29]:
print(iris_data.feature_names) # 리스트 
print(iris_data.data.shape) # .data 하면 numpy 배열 -> shape 
print(iris_data.target) # 넘파이 배열 숫자 


['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
(150, 4)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [30]:
# 학습/테스트 데이터 세트 분리
dt_clf = DecisionTreeClassifier()
iris_data=load_iris() # 데이터 전체 상자 - 딕셔너리 형태의 뭉치
iris_data.data # 상자 안의 문제지 : 넘파이 배열 (숫자들)
iris_data.target  # 상자 안의 정답지 : 넘파일 배열 
iris_data.data.shape # 넘파이의 크기 확인 ex (150,4) 

(150, 4)

In [31]:
# K 폴드
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

In [32]:
kfold = KFold(n_splits=5) # 5개의 폴드 세트로 분리하는 KFold 객체 생성
cv_accuracy =[]# 폴드 세트별 정확도 담을 리스트 객체
print('붓꽃 데이터 세트 크기 :',features.shape[0])

붓꽃 데이터 세트 크기 : 150


In [33]:
for train_index , test_index in kfold.split(features): #split 
 #값 X 번호 - train_index: [2, 3, 4, 5, 6, 7, 8, 9] (공부할 번호) ,test_index: [0, 1] (시험 볼 번호)
    X_train,X_test = features[train_index],features[test_index]
    y_train,y_test = label[train_index],label[test_index]

    #학습 및 예측
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    # 반복시 마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    cv_accuracy.append(accuracy)
print('평균 검증 정확도: ',np.mean(cv_accuracy)) 

평균 검증 정확도:  0.9


In [34]:
## ❇️ skfold 적용 예제 
from sklearn.model_selection import StratifiedKFold

dt_clf = DecisionTreeClassifier(random_state=156)
skfold = StratifiedKFold(n_splits=3)
cv_accuracy=[]

# StratifiedKFold 의 split 호출시 반드시 레이블 데이터 세트 추가 입력 ! 
for train_index , test_index in skfold.split(features,label):
    
    #split()으로 반환된 인덱스를 이용해 학습용 , 검증용 테스트 데이터 추출
    X_train , X_test = features[train_index] , features[test_index]
    y_train , y_test = label[train_index],label[test_index]
    #학습 
    dt_clf.fit(X_train,y_train)
    #예측
    pred = dt_clf.predict(X_test)
    #반복시 마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test,pred),4)
    
    cv_accuracy.append(accuracy)
print('교차 검증별 정확도 :',np.round(cv_accuracy,4)) # 리스트 각각 반올림 
print('평균 검증 정확도 :',np.round(np.mean(cv_accuracy),4))

교차 검증별 정확도 : [0.98 0.94 0.98]
평균 검증 정확도 : 0.9667


In [37]:
# cross_val_score()
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score,cross_validate
iris_data = load_iris()
dt_clf  = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target
scores = cross_val_score(dt_clf,data,label,scoring='accuracy',cv=3)
print('교차 검증별 정확도 :',np.round(cv_accuracy,4)) # 리스트 각각 반올림 
print('평균 검증 정확도 :',np.round(np.mean(cv_accuracy),4))

교차 검증별 정확도 : [0.98 0.94 0.98]
평균 검증 정확도 : 0.9667


In [50]:
# GridSearchCV - 교차검증 + 최적 하이퍼 파라미터 튜닝
from sklearn.model_selection import GridSearchCV
iris_data = load_iris()
#1. 학습 데이터 테스트 데이터분리
X_train , X_test , y_train ,y_test = train_test_split(iris_data.data , iris_data.target ,test_size=0.2,random_state=121)
#2. 객체
dtree = DecisionTreeClassifier()
#3. 파라미터를 딕셔너리 형태로 
parameters = {'max_depth':[1,2,3],'min_samples_split':[2,3]}

#설정
grid_dtree = GridSearchCV(dtree,param_grid=parameters ,cv=3,refit=True)
#학습
grid_dtree.fit(X_train,y_train)

#결과는 딕셔너리라 DataFrame으로 변경
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score']]


params  mean_test_score  rank_test_score
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1

In [54]:
# fit() 수행하면 최고성능의 하이퍼파라미터 , 평가 결과값이 기록됨
print(grid_dtree.best_params_)
print(grid_dtree.best_score_)

{'max_depth': 3, 'min_samples_split': 2}
0.975


In [58]:
# 이미 학습된 estimator로 예측
estimator = grid_dtree.best_estimator_
pred = estimator.predict(X_test)
print(accuracy_score(y_test,pred))

0.9666666666666667


In [63]:
# 데이터 전처리
# 1 ) 레이블 인코딩
from sklearn.preprocessing import LabelEncoder
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder = LabelEncoder()
encoder.fit(items) # 번호 배정 
labels = encoder.transform(items) # 글자를 숫자로 TV -.3 냉장고 ->0 이렇게 
print(labels)
print(encoder.classes_) # 인코딩 값에 대한 원본을 가짐 

[0 1 4 5 3 3 2 2]
['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [73]:
# 2 ) 원-핫 인코딩
from sklearn.preprocessing import OneHotEncoder
import numpy as np 
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

#2차원 ndarray로 변환
items = np.array(items).reshape(-1,1)

#원핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)


In [76]:
#판다스에 원-핫 인코딩 더 쉽게함 
df = pd.DataFrame({'items' : ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df,dtype=int)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         0          1            0          0
6         0          0         1          0            0          0
7         0          0         1          0            0          0

In [90]:
# 표준화 
from sklearn.preprocessing import StandardScaler
iris=load_iris()
iris_data=iris.data
iris_df = pd.DataFrame(data=iris_data ,columns=iris.feature_names)

#객체 
scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df) # transform으로 변환된거 ndarry 이므로 df로 변환

iris_df_scaled = pd.DataFrame(data=iris_scaled , columns = iris.feature_names)
print(iris_df_scaled.mean())
print(iris_df_scaled.var())

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [93]:
# MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
#객체
scaler = MinMaxScaler()
scaler.fit(iris_df) # fit : 정보 설정 
iris_scaled = scaler.transform(iris_df) # 설정정보로 데이터 반환 

iris_df_scaled = pd.DataFrame(data=iris_scaled , columns = iris.feature_names)
print(iris_df_scaled.mean())
print(iris_df_scaled.var())

sepal length (cm)    0.428704
sepal width (cm)     0.440556
petal length (cm)    0.467458
petal width (cm)     0.458056
dtype: float64
sepal length (cm)    0.052908
sepal width (cm)     0.032983
petal length (cm)    0.089522
petal width (cm)     0.100869
dtype: float64


In [99]:
# 주의 ! 테스트 데이터에서 fit()X 학습데이터에 적용된 객체로 transform() 변환
scaler = MinMaxScaler()
train_array = np.arange(0, 11).reshape(-1, 1)
test_array = np.arange(0, 6).reshape(-1, 1)

scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
test_scaled = scaler.transform(test_array)
